[package]
name = "oxide"
version = "0.0.1"
authors = ["wess <wcope@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
libc = "0.2.108"
nix = "0.23.1"
